export const GenreNameConstants = [
  'Acción',
  'Aventura',
  'Artes marciales',
  'Bélico',
  'Biográfico',
  'Ciencia ficción',
  'Ciberpunk',
  'Comedia',
  'Comedia romántica',
  'Costumbrista',
  'Crimen',
  'Distopía',
  'Drama',
  'Drama psicológico',
  'Escolar',
  'Espacial',
  'Espiritual',
  'Erótico',
  'Fantasia oscura',
  'Fantasia épica',
  'Fantasia urbana',
  'Fantasía',
  'Ficción histórica',
  'Gótico',
  'Harem',
  'Histórico',
  'Horror',
  'Juvenil',
  'Lgbtq+',
  'Magia',
  'Misterio',
  'Mitológico',
  'Musical',
  'Paranormal',
  'Policial',
  'Postapocalíptico',
  'Psicológico',
  'Recuentos de la vida',
  'Reencarnación',
  'Romance',
  'Romance contemporáneo',
  'Romance histórico',
  'Samurái',
  'Satírico',
  'Shoujo',
  'Shounen',
  'Sobrenatural',
  'Suspenso',
  'Thriller',
  'Tragedia',
  'Vampiros',
  'Vida cotidiana',
  'Western',
  'Xianxia',
  'Yaoi',
  'Yuri',
] as const;

export type AllowedGenre = (typeof GenreNameConstants)[number];
